<?php
/**
 * Created by PhpStorm.
 * User: menouer
 * Date: 31/05/2018
 * Time: 13:51
 */

    class Dancers_model extends CI_Model
    {

        protected $tableDancer = 'dancer';
        protected $idDancer = 'dancer_id';
        protected $lastDancer = 'dancer_lastname';
        protected $firstDancer = 'dancer_firstname';
        protected $stageNameDancer = 'stage_name';
        protected $soloBool = 'solo_boolean';

        /**
         * Dancers_model constructor.
         */
        function __construct()
        {
            parent::__construct();
            $this->load->database();
        }
        /**
         * @param string $key
         * @return mixed
         */
        public function __get($key)
        {
            return parent::__get($key); // TODO: Change the autogenerated stub
        }

        /**
         * @return string
         */
        public function getTableDancer()
        {
            return $this->tableDancer;
        }

        /**
         * @return string
         */
        public function getIdDancer()
        {
            return $this->idDancer;
        }
        /**
         * @return string
         */
        public function getLastDancer()
        {
            return $this->lastDancer;
        }
        /**
         * @return string
         */
        public function getFirstDancer()
        {
            return $this->firstDancer;
        }
        /**
         * @return string
         */
        public function getStageNameDancer()
        {
            return $this->stageNameDancer;
        }
        /**
         * @return string
         */
        public function getSoloBool()
        {
            return $this->soloBool;
        }

        public function getListDancers()
        {
            $this->load->database();
            return $this->db
                ->select($this->getStageNameDancer(),$this->getFirstDancer(),$this->getLastDancer())
                ->from($this->getTableDancer())
                ->order_by($this->getStageNameDancer());
        }

        public function addDancers($id,$ln,$fn,$sn,$bool)
        {
            $this->load->database();
            $data = array(
                $this->getIdDancer() => $id,
                $this->getLastDancer() => $ln,
                $this->getFirstDancer() => $fn,
                $this->getStageNameDancer() => $sn,
                $this->getSoloBool() => $bool
            );
            return $this->db
                ->insert($this->getTableDancer(),$data);
        }

        public function updateDancer($id,$ln,$fn,$sn,$bool)
        {
            $this->load->database();
            $data = array(
                $this->getIdDancer() => $id,
                $this->getLastDancer() => $ln,
                $this->getFirstDancer() => $fn,
                $this->getStageNameDancer() => $sn,
                $this->getSoloBool() => $bool
            );
            return $this->db
                ->replace($this->getTableDancer(),$data);
        }

        public function deleteDancer($id)
        {
            $this->load->database();
            $data = array($this->getIdDancer() =>$id);
            return $this->db
                ->delete($this->getTableDancer(),$data);
        }

    }