<?php

    class Home_model extends CI_Model{

        protected $tableUser = 'user';
        protected $relationCanBe = 'can_be';
        protected $tableCustomer = 'customer';
        protected $tableDancer = 'dancer';
        protected $tableSchoolAgent = 'school_agent';

        protected $userN = 'username';
        protected $passW = 'password';
        protected $mailA = 'mail_address';

        protected $customerId = 'customer_id';
        protected $valueC = '0';
        protected $dancerId = 'dancer_id';
        protected $valueD = '0';
        protected $schoolAgentId = 'school_agent_id';
        protected $valueSA = '0';

        protected $schoolId = 'school_id'; //for the tables SchoolAgent and Dancer (and School of course,if it should be added)

        protected $customerLast = 'customer_lastname';
        protected $customerFirst = 'customer_firstname';
        protected $customerCity = 'customer_city';
        protected $customerStreet = 'customer_street';
        protected $customerZC = 'customer_zipcode';

        protected $dancerLast = 'dancer_lastname';
        protected $dancerFirst = 'dancer_firstname';
        protected $dancerSN = 'stage_name';
        protected $bool = 'solo_boolean';

        protected $schoolAgLast = 'school_agent_lastname';
        protected $schoolAgFirst = 'school_agent_firstname';
        protected $schoolAgCity = 'school_agent_city';
        protected $schoolAgStreet = 'school_agent_street';
        protected $schoolAgZC = 'school_agent_zipcode';

        function __construct()
        {
            parent::__construct();
            $this->load->database();
        }
        public function __get($key)
        {
            return parent::__get($key); // TODO: Change the autogenerated stub
        }

        /**
         * @return string
         */
        public function getTableUser()
        {
            return $this->tableUser;
        }
        /**
         * @return string
         */
        public function getTableCustomer()
        {
            return $this->tableCustomer;
        }
        /**
         * @return string
         */
        public function getTableDancer()
        {
            return $this->tableDancer;
        }
        /**
         * @return string
         */
        public function getTableSchoolAgent()
        {
            return $this->tableSchoolAgent;
        }
        /**
         * @return string
         */
        public function getRelationCanBe()
        {
            return $this->relationCanBe;
        }

        /**
         * @return string
         */
        public function getUserN()
        {
            return $this->userN;
        }
        /**
         * @return string
         */
        public function getPassW()
        {
            return $this->passW;
        }
        /**
         * @return string
         */
        public function getMailA()
        {
            return $this->mailA;
        }

        /**
         * @return string
         */
        public function getCustomerId()
        {
            return $this->customerId;
        }
        /**
         * @return string
         */
        public function getCustomerLast()
        {
            return $this->customerLast;
        }
        /**
         * @return string
         */
        public function getCustomerFirst()
        {
            return $this->customerFirst;
        }
        /**
         * @return string
         */
        public function getCustomerCity()
        {
            return $this->customerCity;
        }
        /**
         * @return string
         */
        public function getCustomerStreet()
        {
            return $this->customerStreet;
        }
        /**
         * @return string
         */
        public function getCustomerZC()
        {
            return $this->customerZC;
        }

        /**
         * @return string
         */
        public function getDancerId()
        {
            return $this->dancerId;
        }
        /**
         * @return string
         */
        public function getDancerLast()
        {
            return $this->dancerLast;
        }
        /**
         * @return string
         */
        public function getDancerFirst()
        {
            return $this->dancerFirst;
        }
        /**
         * @return string
         */
        public function getDancerSN()
        {
            return $this->dancerSN;
        }
        /**
         * @return string
         */
        public function getBool()
        {
            return $this->bool;
        }
        /**
         * @return string
         */
        public function getSchoolId()
        {
            return $this->schoolId;
        }

        /**
         * @return string
         */
        public function getSchoolAgentId()
        {
            return $this->schoolAgentId;
        }
        /**
         * @return string
         */
        public function getSchoolAgLast()
        {
            return $this->schoolAgLast;
        }
        /**
         * @return string
         */
        public function getSchoolAgFirst()
        {
            return $this->schoolAgFirst;
        }
        /**
         * @return string
         */
        public function getSchoolAgCity()
        {
            return $this->schoolAgCity;
        }
        /**
         * @return string
         */
        public function getSchoolAgStreet()
        {
            return $this->schoolAgStreet;
        }
        /**
         * @return string
         */
        public function getSchoolAgZC()
        {
            return $this->schoolAgZC;
        }

        /**
         * @param string $valueC
         */
        public function setValueC($valueC)
        {
            $this->valueC = $valueC;
        }
        /**
         * @param string $valueD
         */
        public function setValueD($valueD)
        {
            $this->valueD = $valueD;
        }
        /**
         * @param string $valueSA
         */
        public function setValueSA($valueSA)
        {
            $this->valueSA = $valueSA;
        }

        public function getDataUser()
        {
            $this->load->database();
            return $this->db
                ->select($this->getUserN(),$this->getPassW(),$this->getMailA())
                ->from($this->getTableUser());
        }

        public function addVisitor($userName, $passWord, $mailAdd, $cL, $cF, $cC, $cS, $cZ)
        {
            $this->load->database();
            $id = $this->db->get($this->getCustomerId())->from($this->getRelationCanBe())->order_by($this->getCustomerId(),'DESC')->limit(1);
            $id++;
            $dataU = array(
                $this->getUserN() => $userName,
                $this->getPassW() => $passWord,
                $this->getMailA() => $mailAdd
            );
            $dataC = array(
                $this->getCustomerId() => $id,
                $this->getCustomerLast() => $cL,
                $this->getCustomerFirst() => $cF,
                $this->getCustomerCity() => $cC,
                $this->getCustomerStreet() => $cS,
                $this->getCustomerZC() => $cZ
            );
            $dataRel = array(
                $this->getUserN() => $userName,
                $this->getPassW() => $passWord,
                $this->getMailA() => $mailAdd,
                $this->getCustomerId() => $id
            );
            $this->db->insert($this->getTableUser(),$dataU);
            $this->db->insert($this->getTableCustomer(),$dataC);
            $this->db->insert($this->getRelationCanBe(),$dataRel);
        }
        public function addDancer($userName,$passWord,$mailAdd,$dL,$dF,$dSN,$dBool){
            $this->load->database();
            $id = $this->db->get($this->getDancerId())->from($this->getRelationCanBe())->order_by($this->getDancerId(),'DESC')->limit(1);
            $id++;
            $dataU = array(
                $this->getUserN() => $userName,
                $this->getPassW() => $passWord,
                $this->getMailA() => $mailAdd
            );
            $dataD = array(
                $this->getDancerId() => $id,
                $this->getDancerLast() => $dL,
                $this->getDancerFirst() => $dF,
                $this->getDancerSN() => $dSN,
                $this->getBool() => $dBool
            );
            $dataRel = array(
                $this->getUserN() => $userName,
                $this->getPassW() => $passWord,
                $this->getMailA() => $mailAdd,
                $this->getDancerId() => $id
            );
            $this->db->insert($this->getTableUser(),$dataU);
            $this->db->insert($this->getTableDancer(),$dataD);
            $this->db->insert($this->getRelationCanBe(),$dataRel);
        }

    }
