<?php
/**
 * Created by PhpStorm.
 * User: menouer
 * Date: 31/05/2018
 * Time: 13:52
 */

    class Shows_model extends CI_Model{

        protected $tableEvent = 'event';
        protected $tableShow = 'show';
        protected $tableScene = 'scene';

        protected $eventId = 'event_id';
        protected $eventName = 'event_name';
        protected $placesNumber = 'places_number';
        protected $eventPlace = 'event_place';
        protected $eventTime = 'event_time';
        protected $sceneId = 'scene_id';

        protected $showDuration = 'show_duration';

        protected $sceneName = 'scene_name';

        /**
         * Shows_model constructor.
         */
        function __construct()
        {
            parent::__construct();
            $this->load->database();
        }

        /**
         * @param string $key
         * @return mixed
         */
        public function __get($key)
        {
            return parent::__get($key); // TODO: Change the autogenerated stub
        }

        /**
         * @return string
         */
        public function getTableEvent()
        {
            return $this->tableEvent;
        }
        /**
         * @return string
         */
        public function getTableShow()
        {
            return $this->tableShow;
        }
        /**
         * @return string
         */
        public function getTableScene()
        {
            return $this->tableScene;
        }

        /**
         * @return string
         */
        public function getEventId()
        {
            return $this->eventId;
        }
        /**
         * @return string
         */
        public function getEventName()
        {
            return $this->eventName;
        }
        /**
         * @return string
         */
        public function getEventPlace()
        {
            return $this->eventPlace;
        }
        /**
         * @return string
         */
        public function getEventTime()
        {
            return $this->eventTime;
        }
        /**
         * @return string
         */
        public function getPlacesNumber()
        {
            return $this->placesNumber;
        }
        /**
         * @return string
         */
        public function getSceneId()
        {
            return $this->sceneId;
        }
        /**
         * @return string
         */
        public function getSceneName()
        {
            return $this->sceneName;
        }
        /**
         * @return string
         */
        public function getShowDuration()
        {
            return $this->showDuration;
        }

        public function getListShows()
        {
            $this->load->database();
            return $this->db
                ->select($this->getEventName(),$this->getPlacesNumber(),$this->getEventPlace(),$this->getSceneName())
                ->from($this->getTableEvent())
                ->join($this->getTableShow(),$this->getTableEvent().'.'.$this->getEventId().'='.$this->getTableShow().'.'.$this->getEventId())
                ->join($this->getTableScene(),$this->getTableEvent().'.'.$this->getSceneId().'='.$this->getTableScene().'.'.$this->getSceneId())
                ->order_by($this->getEventTime());
        }

        public function addShow($id,$name,$nb,$place,$date,$duration,$sceName)
        {
            $this->load->database();
            $sceneIdentifier = $this->db->select($this->getSceneId())->from($this->getTableScene())->where($this->getSceneName().'='.$sceName);
            $data = array(
                $this->getEventId() => $id,
                $this->getEventName() => $name,
                $this->getPlacesNumber() => $nb,
                $this->getEventPlace() => $place,
                $this->getEventTime() => $date,
                $this->getShowDuration() => $duration,
                $this->getSceneId() => $sceneIdentifier
            );
            return $this->db
                ->insert($this->getTableShow(),$data);
        }

        public function updateShow($id,$name,$nb,$place,$date,$duration,$sceName)
        {
            $this->load->database();
            $sceneIdentifier = $this->db->select($this->getSceneId())->from($this->getTableScene())->where($this->getSceneName().'='.$sceName);
            $data = array(
                $this->getEventId() => $id,
                $this->getEventName() => $name,
                $this->getPlacesNumber() => $nb,
                $this->getEventPlace() => $place,
                $this->getEventTime() => $date,
                $this->getShowDuration() => $duration,
                $this->getSceneId() => $sceneIdentifier
            );
            return $this->db
                ->replace($this->getTableShow(),$data);
        }

        public function deleteShow($id)
        {
            $this->load->database();
            $data = array($this->getEventId() =>$id);
            return $this->db
                ->delete($this->getTableShow(),$data);
        }
    }