<?php
/**
 * Created by PhpStorm.
 * User: menouer
 * Date: 31/05/2018
 * Time: 13:51
 */

    class Tournaments_model extends CI_Model{

        protected $tableEvent = 'event';
        protected $tableTour = 'tournament';
        protected $tableScene = 'scene';

        protected $eventId = 'event_id';
        protected $eventName = 'event_name';
        protected $placesNumber = 'places_number';
        protected $eventPlace = 'event_place';
        protected $eventTime = 'event_time';
        protected $sceneId = 'scene_id';

        protected $participants = 'participants_number';

        protected $sceneName = 'scene_name';

        /**
         * Tournaments_model constructor.
         */
        function __construct()
        {
            parent::__construct();
            $this->load->database();
        }
        /**
         * @param string $key
         * @return mixed
         */
        public function __get($key)
        {
            return parent::__get($key); // TODO: Change the autogenerated stub
        }

        /**
         * @return string
         */
        public function getTableEvent()
        {
            return $this->tableEvent;
        }
        /**
         * @return string
         */
        public function getTableTour()
        {
            return $this->tableTour;
        }
        /**
         * @return string
         */
        public function getTableScene()
        {
            return $this->tableScene;
        }

        /**
         * @return string
         */
        public function getEventId()
        {
            return $this->eventId;
        }
        /**
         * @return string
         */
        public function getEventName()
        {
            return $this->eventName;
        }
        /**
         * @return string
         */
        public function getEventTime()
        {
            return $this->eventTime;
        }
        /**
         * @return string
         */
        public function getEventPlace()
        {
            return $this->eventPlace;
        }
        /**
         * @return string
         */
        public function getPlacesNumber()
        {
            return $this->placesNumber;
        }

        /**
         * @return string
         */
        public function getParticipants()
        {
            return $this->participants;
        }

        /**
         * @return string
         */
        public function getSceneId()
        {
            return $this->sceneId;
        }
        /**
         * @return string
         */
        public function getSceneName()
        {
            return $this->sceneName;
        }

        public function getListTours()
        {
            $this->load->database();
            return $this->db
                ->select($this->getEventName(),$this->getPlacesNumber(),$this->getEventPlace(),$this->getSceneName())
                ->from($this->getTableEvent())
                ->join($this->getTableTour(),$this->getTableEvent().'.'.$this->getEventId().'='.$this->getTableTour().'.'.$this->getEventId())
                ->join($this->getTableScene(),$this->getTableEvent().'.'.$this->getSceneId().'='.$this->getTableScene().'.'.$this->getSceneId())
                ->order_by($this->getEventTime());
        }

        public function addTour($id,$name,$nb,$place,$date,$particip,$sceName)
        {
            $this->load->database();
            $sceneIdentifier = $this->db->select($this->getSceneId())->from($this->getTableScene())->where($this->getSceneName().'='.$sceName);
            $data = array(
                $this->getEventId() => $id,
                $this->getEventName() => $name,
                $this->getPlacesNumber() => $nb,
                $this->getEventPlace() => $place,
                $this->getEventTime() => $date,
                $this->getParticipants() => $particip,
                $this->getSceneId() => $sceneIdentifier
            );
            return $this->db
                ->insert($this->getTableTour(),$data);
        }

        public function updateTour($id,$name,$nb,$place,$date,$particip,$sceName)
        {
            $this->load->database();
            $sceneIdentifier = $this->db->select($this->getSceneId())->from($this->getTableScene())->where($this->getSceneName().'='.$sceName);
            $data = array(
                $this->getEventId() => $id,
                $this->getEventName() => $name,
                $this->getPlacesNumber() => $nb,
                $this->getEventPlace() => $place,
                $this->getEventTime() => $date,
                $this->getParticipants() => $particip,
                $this->getSceneId() => $sceneIdentifier
            );
            return $this->db
                ->replace($this->getTableTour(),$data);
        }

        public function deleteTour($id)
        {
            $this->load->database();
            $data = array($this->getEventId() =>$id);
            return $this->db
                ->delete($this->getTableTour(),$data);
        }
    }